<?php 

//====================================================
// Creación e Inserción de Base Datos, Tablas y Datos
//====================================================

// Crear Tabla
$sqlCreateBDTable = "CREATE TABLE t_album_".$usuario." (id_laminita int(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, laminitaLadoA varchar(10) COLLATE utf8_spanish2_ci NOT NULL, laminitaLadoB text COLLATE utf8_spanish2_ci NOT NULL, visualizar int(2) NOT NULL, fechaLaminita date NOT NULL);";
$resulSqlTBD = $conexion->query($sqlCreateBDTable);


// Insertar datos en la Base de datos
$sqlInsertTable = "INSERT INTO t_album_".$usuario." (id_laminita, laminitaLadoA, laminitaLadoB,  visualizar) VALUES 
(1,'173R96','Santuario de Flora y Fauna Iguaque: El Santuario es de importancia vital como proveedor de servicios ecosistémicos, como el abastecimiento de agua para el consumo humano.' ,0),
(2,'UF84U0','Lago de Tota: Es el lago de mayor extensidad en el país, Representa el 13,55% de la reserva de agua de Colombia. Abastece de agua potable aproximadamente a 250000 personas.' ,0),
(3,'TQMAPU','Parque Nacional Natural el Cocuy: Cuenta con 150 lagunas enriquecen la oferta hídrica de la Sierra, páramos y una gran franja de bosque andino que albergan gran diversidad de especies de fauna y flora.' ,0),
(4,'ZY3LKX','Pristimantis macrummendozai: Especie endémica de Arcabuco (Boyacá), su color oscuro le permite camuflarse pero son sus ‘cejas’, la que la hacen única.' ,0),
(5,'C1I4TY','Niceforonia Nana: Páramo de La Rusia en Duitama (Boyacá), considerada en peligro debido a su rareza y la desaparición de sus hábitats originales.' ,0),
(6,'R7NY2W','Guartinaja: Animal vertebrado, mamífero y roedor (pariente del conejo). Está en peligro de extinción debido a la destrucción progresiva de su hábitat.' ,0),
(7,'BR198G','Oso de anteojos: Se encuentra en los complejos de páramos de Mamapacha - Bijagual y Ocetá - Pisba - Cocuy y la Serranía de las Quinchas del departamento de Boyacá.' ,0),
(8,'AAE9TH','Tigrillo: Algunas de las mayores amenazas a las que se enfrenta son la expansión de la infraestructura vial y el crecimiento de la población humana.' ,0),
(9,'6YCAWJ','La quincha de Soatá: Vive en zonas áridas y en los bordes de los bosques en los Andes, en los departamentos de Santander y Boyacá. ​ Está amenazado por pérdida de hábitat.' ,0),
(10,'RA79WD','Pyrrhura calliptera: Se encuentra en Colombia entre 1700 y 3400 m sobre el nivel del mar en ambas vertientes de la cordillera oriental desde el sur de Boyacá hasta el suroccidente de Cundinamarca.' ,0),
(11,'5Q4JT7','PNN Los Picachos: ubicado entre Meta y Caquetá, conecta los ecosistemas andinos, amazónicos y orinocenses, almacena 160 ton Carbono/ha y posee un alto rendimiento hídrico.' ,0),
(12,'TPPZXJ','PNN Chingaza: situado entre Cundinamarca y Meta. Provee el 80% del agua para consumo en Bogotá, es hábitat del oso de anteojos, el venado cola blanca y el cóndor de los Andes.' ,0),
(13,'DPUPDW','PNN Sierra de la Macarena: conocido por los paisajes de caño Cristales; sus bosques inundables son importantes para el flujo de materia-energía entre ecosistemas.' ,0),
(14,'CD5WW2','PNN Tinigua: ubicado en el Meta, posee alta diversidad biológica y atractivos histórico culturales como petroglifos y pictografías de las etnias Tinigua y Guayabero. ' ,0),
(15,'E9D6T1','PNN Sumapaz:, localizado entre Cundinamarca, Huila y Meta, contiene la mayor área de ecosistema de páramo, provee regulación hídrica de cuencas y soporte de biodiversidad.' ,0),
(16,'2DU3N6','Aprovechar la luz natural y apagar las luces cuando no se necesitan permite ahorrar entre 8 y 20% de energía y aumenta la vida útil de las luminarias.' ,0),
(17,'A3ZP43','Miles de animales están muriendo por atrapamiento o consumo de plástico. Evita usar pitillos, comprar bebidas en recipientes plásticos y el uso de bolsas prescindibles.' ,0),
(18,'HA5S3C','Solo el 3% del agua del planeta es dulce, y solo 1% de esta agua está disponible para consumo. En Colombia por cada 10 litros de agua potable se están desperdiciando 4.' ,0),
(19,'IMAVC2','La alimentación sustentable promueve el consumo de alimentos orgánicos, producidos cerca del lugar de compra, que estén en temporada y que sus empaques o envases sean amiga bles.' ,0),
(20,'5WPIXX','ARPE Humedal El Charco: declarada y delimitada en 2011 busca preservar la fauna y flora del piedemonte llanero, la regulación hídrica y proveer espacios de investigación.' ,0),
(21,'6M0ULP','Una colilla de cigarrillo puede contaminar hasta 8 litros de agua. No la arrojes al suelo.' ,0),
(22,'8YY1TY','Sabías que una botella de vidrio se demora más de 4000 años en degradarse. Recicla.' ,0),
(23,'JNARQL','Sabías que un pañal desechable se demora entre 100 y 450 años en degradarse. En el mercado ya hay opciones más ecológicas.' ,0),
(24,'B88X7J','El plástico proviene del petróleo un proceso de alto impacto ambiental y social, se demora cientos de años en degradarse.  Evitemos el plástico de un solo uso.' ,0),
(25,'UEEIBF','Sabías que una bolsa de plástico se demora más de 150 años en degradarse y la usamos por unos poco minutos. Las bolsas reutilizables son una mejor opción.' ,0),
(26,'YLVGUU','Sabías que una botella plástica se puede demorar hasta 1000 años en degradarse. Carga tu propia botella reutilizable.' ,0),
(27,'TTEL44','Un pitillo plástico se demora cientos de años en degradarse porque es un derivado del petróleo, y solo lo usamos por unos minutos. Di NO al pitillo.' ,0),
(28,'ETJF63','Sabías que si montas en bicicleta, por cada kilómetro recorrido estas evitando la generación de 300 gramos de CO2 a la atmósfera, principal causante del calentamiento global.' ,0),
(29,'VFJ2XM','Sabías que si utilizas iluminación LED puedes ahorrar hasta el 85% del consumo de energía con otro tipo de luminarias y ayudas a reducir las emisiones de gases que aportan al calentamiento global.' ,0),
(30,'P99FC3','Sabías que desde la estrategia de Desarrollo Comunitario de al DRSU mediante un trabajo articulado con Ing. Ambiental realizó el proyecto comunitario de Agricultura Urbana en el Centro de Proyección Social de Suba.' ,0),
(31,'4IR8C5','Sabías que desde la DRSU en su estrategia de Desarrollo Comunitario desarrolló la campaña “Por una ciudad sin contaminación” con el Facultad de Ing. Industrial en el CPS de Chapinero.' ,0),
(32,'POPT4A',' Sabías que desde la DRSU se apoyó el proyecto Aula Agroecológica en el Mirador de los Nevados de Suba se realiza intercambio de saberes, transferencia de conocimientos y tecnología.' ,0),
(33,'M495RA','Desde el DRSU se realizó el Proyecto de Huertas Escolares y permacultura en el programa “Escuelas Protectoras” del CPS de Cazucá y Administración de Empresas Agropecuarias DUAD.' ,0),
(34,'MTNS9T','Desde el programa “Escuelas Protectoras” la DRSU e Ingeniería Ambiental se construyó el sistema de riego para la huerta escolar del Colegio Luís Carlos Galán beneficiando 1400 estudiantes.' ,0),
(35,'Y2DVET','A través de la Política Ambiental (Acuerdo 42 de 2017) la Universidad Santo Tomás se compromete a  favorecer la protección del ambiente y a promover el  pensamiento ético - ambiental' ,0),
(36,'G2VXGP','“El desafío urgente de proteger nuestra casa común incluye la preocupación de unir a toda la familia humana en la búsqueda de un desarrollo sostenible e integral, pues sabemos que las cosas pueden cambiar.” Papa Francisco' ,0),
(37,'1NWLVL','Sabías que en el Campus San Alberto Magno de Bogotá contamos con un generador fotovoltaíco de 30KwH que va a generar el 15% de la energía consumida en esta sede.' ,0),
(38,'Q6YR0Z','Sabías que al hacer la transición a LED la Universidad está buscando reducir el consumo de energía, la generación de Gases Efecto Invernadero y la producción de residuos peligrosos.' ,0),
(39,'EQIOH8','Sabías que el papel que se compra en la Universidad proviene del bagazo de caña de azúcar, no tiene ácidos ni cloro. Es importante su uso racional para proteger el ambiente.' ,0),
(40,'17W6XR','Sabías que en el 2018 la Universidad Santo Tomás Sede Principal recuperó más de 18 toneladas de residuos reciclables. Valoremos el trabajo del personal de Casa Limpia.' ,0),
(41,'3MHRXJ','Sabías que en las diferentes sedes de Bogotá contamos con más de 35 bici parqueaderos gratuitos. Comprometidos con la movilidad sostenible.' ,0),
(42,'MBHZAZ','42 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(43,'J4TT1I','43 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(44,'BEGKJC','44 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(45,'VQ77D2','45 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(46,'NB9S5S','46 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(47,'XMJ9JA','47 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(48,'IEJKMA','48 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(49,'99LLE1','49 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(50,'H87FKE','50 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(51,'Z42XYP','51 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(52,'DA4U7P','52 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(53,'2JKPJB','53 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(54,'JKJ6FC','54 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(55,'K362V6','55 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(56,'HT7YKW','56 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(57,'WGZUYY','57 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(58,'KK1RQC','58 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(59,'GHIXXT','59 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(60,'HDMXHZ','60 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(61,'YAX1HI','61 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(62,'AZHBAD','62 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(63,'2ODP2J','63 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(64,'9BOVT2','64 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(65,'JW42N3','65 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(66,'UQG96K','66 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(67,'TY85LX','67 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(68,'TM7C9H','68 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(69,'O1TUWS','69 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(70,'G5KDLK','70 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(71,'PSDC0N','71 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(72,'5QQ6E8','72 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(73,'D5PLPG','73 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(74,'47WTQ1','74 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(75,'G874TY','75 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(76,'3MARPK','76 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(77,'1HRV67','77 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(78,'DA5JGJ','78 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(79,'ZLB7N8','79 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(80,'M64A1S','80 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(81,'4WT7D0','81 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(82,'UMAC7Q','82 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(83,'IWLR0O','83 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(84,'HDCND0','84 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(85,'17JBSP','85 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(86,'5MFA0M','86 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(87,'Y7S3ZI','87 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(88,'KMOWXN','88 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(89,'74DNRR','89 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(90,'KYYX55','90 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(91,'F4AO26','91 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(92,'4BX1E8','92 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(93,'X305EC','93 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(94,'1C94V8','94 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(95,'QMQA0H','95 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(96,'V6SBO8','96 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(97,'Q0P8GH','97 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(98,'TEENUY','98 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(99,'SSX7RB','99 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(100,'5Z63HF','100 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(101,'OI2O1T','101 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(102,'39P2FZ','102 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(103,'EBG791','103 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(104,'4EBIXZ','104 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(105,'LK0BTR','105 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(106,'HNCEV4','106 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(107,'49BQ6Y','107 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(108,'HL3FF6','108 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(109,'HM7NP2','109 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(110,'DM3C7Q','110 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(111,'KVNKXQ','111 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(112,'DO1M1F','112 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(113,'57IHR9','113 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(114,'Q7PBHZ','114 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(115,'EUVD7Z','115 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(116,'3I486D','116 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(117,'H1WAEH','117 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(118,'ZU6P2F','118 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(119,'9OTACQ','119 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(120,'ICRWXI','120 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(121,'Y1KVN0','121 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(122,'NBZOPN','122 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(123,'PGNOUU','123 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(124,'6U94CU','124 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(125,'QSAZDQ','125 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(126,'19DLSB','126 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(127,'CVIV3L','127 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(128,'AON8QE','128 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(129,'DD1PZO','129 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(130,'HBQTY5','130 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(131,'RS453R','131 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(132,'C74IKY','132 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(133,'Z7MLZ7','133 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(134,'XV2NPW','134 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(135,'BAN9GW','135 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(136,'6Z6ISN','136 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(137,'ACU2IZ','137 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(138,'HOHG7O','138 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(139,'14LS81','139 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(140,'3OBL0L','140 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(141,'P4ATYN','141 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(142,'972YIL','142 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(143,'7OO9HJ','143 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(144,'4G3QHB','144 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(145,'IR0ICW','145 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(146,'U1Z0TI','146 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(147,'EPE1J0','147 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(148,'R7OJPX','148 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(149,'BFOH80','149 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(150,'FNA5RR','150 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(151,'YYBLZX','151 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(152,'UV5Y9F','152 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(153,'JM0DC9','153 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(154,'AXQ6WK','154 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(155,'ZEV4UZ','155 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(156,'551J5F','156 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(157,'E2JKQ2','157 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(158,'ZBR45M','158 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(159,'C7KL9Y','159 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(160,'WGTOIF','160 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(161,'F7DVTA','161 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(162,'U01BNX','162 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(163,'9N2XKH','163 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(164,'TEM2DU','164 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(165,'HCFG32','165 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(166,'YSP9KL','166 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(167,'C7LPH7','167 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(168,'GA0XCN','168 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(169,'U4466Z','169 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(170,'7WZ7EE','170 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(171,'SPKLIX','171 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(172,'BPKP0T','172 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(173,'WPRGUM','173 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(174,'TUPAFG','174 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(175,'B7SSJE','175 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(176,'13RQ5Z','176 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(177,'7EY3YU','177 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(178,'GPN7UL','178 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(179,'CN3QRA','179 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(180,'B63SR9','180 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(181,'NF6528','181 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(182,'TAC7UU','182 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(183,'6MJB7K','183 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(184,'WN2DUN','184 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(185,'59DHU6','185 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(186,'HXEMP1','186 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(187,'0BX25M','187 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(188,'UX67MH','188 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(189,'GMWU1Q','189 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(190,'FEEZB4','190 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(191,'HWFBAI','191 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(192,'VDC8GJ','192 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(193,'6ALIYY','193 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(194,'84JT13','194 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(195,'16ZVDE','195 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(196,'2T0Q4U','196 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(197,'YXSHU2','197 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(198,'J5MXAL','198 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(199,'5KZX88','199 LADO B Lorem ipsum dolor sit amet, elit. Sunt non commodi asperiores fuga quos ratione esse totam laborum quam blanditiis qui culpa maxime eum officia doloribus aut laboriosam 1' ,0),
(200,'QPXRJJ','Nuestra Universidad cumple 437 años: para el 13 de junio, pero de 1580, la Universidad Santo Tomás fue fundada por la Orden de Predicadores, siendo así el Primer Claustro Universitario de Colombia.' ,0)";
$resulSqlIBD = $conexion->query($sqlInsertTable);
?>